### ISSUE TITLE
주의사항 2번에 보면 table명과 column명에 대소문자 구별

### ISSUE THREAD

**Issue by tojslee** [vesselofgod/DB_Project#3]
table명과 column 명에 대소문자 구별하라고 하는데 그 구별이라는게 그냥 "" 붙이는거로 해결되는 거를 말하는건가?

**Comment by vesselofgod** [comment]
그냥 "가 아니라 escape 를 써서해야할껄?
만약 " 안붙이면 대소문자를 구별을 못하고 그냥 "를 붙이면 table이름에 "테이블 이름"인 것들밖에 인식을 못함

예를 들어서 table이름이 Building이라는 게 있으면
실제로는 building을 해도 접근이 가능하게 되고,(대소문자 구별 X), 그냥 "를 쓰면 아예 없는 relation이라고 뜨니까 \" 테이블이름  \"
처리를 해줘야 한다는 걸로 이해했어

**Comment by vesselofgod** [comment]
아 근데 방금 "\""+tableList[i].trim()+"\""이런식으로 써봤는데도 대소문자 구별 못하던데?

**Comment by tojslee** [comment]
우리가 지금 한게 잘못되었다는건가?
테이블이름 처리를 그러면 프로그램에 인풋으로 building으로 넣었을 때 쿼리를 만들 때 "building"이렇게 처리해줘야 한다는건가?
