### ISSUE TITLE
미구현 주의사항들 정리

### ISSUE THREAD

**Issue by vesselofgod** [vesselofgod/DB_Project#4]
![image](https://user-images.githubusercontent.com/18081105/69499250-77731180-0f33-11ea-9647-49a90024e25c.png)

![image](https://user-images.githubusercontent.com/18081105/69499267-8d80d200-0f33-11ea-96d1-bede3266dbbb.png)

**Comment by vesselofgod** [comment]
4번은 해결완료

**Comment by vesselofgod** [comment]
9번 근데 postgresql에서 돌아가는지 잘 모름. (mySQL에선 확실히 돌아가던데..)

**Comment by tojslee** [comment]
나 9번 뭔지 모르겠어
아예 어떤 쿼리든 생성할 때 앞에 public을 붙여줘야 한다는건가?

**Comment by vesselofgod** [comment]
9번 해결해서 이미 짬
